# spring:
#   datasource:
#     type: com.zaxxer.hikari.HikariDataSource
#     url: jdbc:h2:mem:TEST
#     driver-class-name: org.h2.Driver
#     username: username
#     password: password
#     hikari:
#       idle-timeout: 10000

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./resources/db
    driver-class-name: org.h2.Driver
    username: sanskriti
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect